try:
    x = unknown()
except ValueError:
    pass
except Exception:
    pass
except:
    pass
finally:
    pass

try:
    y = 1 / 0
except:
    pass
